#!/usr/bin/env python3
"""
Compile the problem bank from its source of truth.

    problems/ESE2030-NNNN.yaml   (hand-editable, one file per problem)
        |
        v
    problems.json                (one document, for quiz_me.py and for AI assistants)
    by_week/weekNN_<slug>.md     (study views, one per LAEF 2E chapter / course week)
    by_source/<sem>-<inst>.md    (study views, one per exam instrument)
    COVERAGE.md                  (problems per week and per skill; which skills are untested)

Everything this script writes is GENERATED. Never hand-edit the outputs; edit the
YAML and re-run. The build refuses to run if validate.py reports errors, so a
broken record can never reach problems.json.

Usage:
    python scripts/compile.py            # rebuild everything
    python scripts/compile.py --check    # validate only, write nothing
"""
import io
import re
import sys
import json
import shutil
import argparse
import datetime as dt
from pathlib import Path
from collections import Counter, defaultdict

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent))
import validate as V

ROOT = Path(__file__).resolve().parent.parent
PROBLEMS = ROOT / 'problems'
SKILLS = ROOT / 'schema' / 'skills.json'
JSON_OUT = ROOT / 'problems.json'
BY_WEEK = ROOT / 'by_week'
BY_SOURCE = ROOT / 'by_source'
COVERAGE = ROOT / 'COVERAGE.md'

SCHEMA_VERSION = '2.1'


def load():
    recs = []
    for p in sorted(PROBLEMS.glob('ESE2030-*.yaml')):
        with io.open(p, encoding='utf-8') as f:
            recs.append(yaml.safe_load(f))
    with io.open(SKILLS, encoding='utf-8') as f:
        skills = json.load(f)
    return recs, skills


def slug(s: str) -> str:
    s = re.sub(r'&', 'and', s.lower())
    s = re.sub(r'[^a-z0-9]+', '_', s).strip('_')
    return s


def titlecase(s: str) -> str:
    return s.title().replace(' Ai', ' AI').replace('Svd', 'SVD').replace('Pca', 'PCA')


def week_title(skills, w):
    return titlecase(skills['weeks'].get(str(w), {}).get('title', f'WEEK {w}'))


def difficulty_of(rec):
    """DIFFICULTY is not yet a schema field; it lives in notes as 'difficulty: X'."""
    m = re.search(r'difficulty:\s*([^|]+)', rec.get('notes') or '')
    return m.group(1).strip() if m else None


def source_key(s):
    return f"{s['semester']}-{s['instrument']}"


# ------------------------------------------------------------------ JSON

def write_json(recs, skills):
    by_week = Counter(r['week'] for r in recs if r['week'])
    by_source = Counter(source_key(s) for r in recs for s in r['sources'])
    doc = {
        'metadata': {
            'course': 'ESE 2030',
            'title': 'Linear Algebra for Engineers',
            'text': 'Linear Algebra: Essence & Form, second edition',
            'schema_version': SCHEMA_VERSION,
            'schema': 'schema/problem.schema.json',
            'skills_index': 'schema/skills.json',
            'generated': dt.datetime.now().isoformat(timespec='seconds'),
            'total_problems': len(recs),
            'by_status': dict(sorted(Counter(r['status'] for r in recs).items())),
            'by_week': {str(k): by_week[k] for k in sorted(by_week)},
            'by_source': dict(sorted(by_source.items())),
            'weeks': {k: v['title'] for k, v in skills['weeks'].items()},
            'note': 'GENERATED by scripts/compile.py from problems/*.yaml. Do not hand-edit.',
        },
        'problems': recs,
    }
    with io.open(JSON_OUT, 'w', encoding='utf-8', newline='\n') as f:
        json.dump(doc, f, indent=1, ensure_ascii=False)
        f.write('\n')


# ------------------------------------------------------------------ markdown

def md_problem(r, skills):
    L = []
    src = ', '.join(f"{s['semester']} {s['instrument']} #{s['position']}" for s in r['sources'])
    meta = [f"week {r['week']}" if r['week'] else 'week ?', src, r['status']]
    if r.get('legacy_id'):
        meta.append(f"legacy {r['legacy_id']}")
    d = difficulty_of(r)
    if d:
        meta.append(d)
    L.append(f"## {r['id']}")
    L.append('*' + ' · '.join(meta) + '*  ')
    if r['skills']:
        names = []
        for sid in r['skills']:
            w = sid[1:3].lstrip('0')
            names.append(f"`{sid}` {skills['weeks'].get(w, {}).get('skills', {}).get(sid, '')}")
        L.append('skills: ' + '; '.join(names) + '  ')
    if r['topics']:
        L.append('topics: ' + ', '.join(r['topics']))
    L.append('')
    L.append(r['statement'].strip())
    L.append('')
    for fig in r['figures']:
        L.append(f'![{fig}](../images/{fig})')
        L.append('')
    for c in r['choices']:
        L.append(f"- **({c['label']})** {c['text'].strip()}")
    L.append('')
    a = r['answer']
    L.append('<details><summary>Answer</summary>')
    L.append('')
    if a['correct']:
        tag = '' if a['verified'] else ' *(unverified)*'
        L.append(f"**Correct: ({a['correct']})**{tag}" +
                 (f"  — partial credit: {', '.join(a['partial_credit'])}" if a['partial_credit'] else ''))
    else:
        L.append('**No answer key** (survey item or key not yet found).')
    L.append('')
    if a.get('explanation'):
        L.append(a['explanation'].strip())
        L.append('')
    if a.get('key_insight'):
        L.append(f"*Key insight:* {a['key_insight'].strip()}")
        L.append('')
    if a.get('distractor_rationale'):
        L.append('Why the distractors tempt:')
        for k, v in sorted(a['distractor_rationale'].items()):
            L.append(f"- ({k}) {v.strip()}")
        L.append('')
    L.append('</details>')
    L.append('')
    L.append('---')
    L.append('')
    return '\n'.join(L)


def write_views(recs, skills):
    for d in (BY_WEEK, BY_SOURCE):
        if d.exists():
            shutil.rmtree(d)
        d.mkdir()

    active = [r for r in recs if r['status'] != 'retired-2e']
    for w in range(1, 14):
        title = week_title(skills, w)
        rows = [r for r in recs if r['week'] == w]
        L = [f"# Week {w}: {title}", '',
             f"*{len(rows)} problems. GENERATED by scripts/compile.py — edit problems/*.yaml, not this file.*", '']
        if not rows:
            L.append('_No problems yet for this week._')
        for r in rows:
            L.append(md_problem(r, skills))
        (BY_WEEK / f'week{w:02d}_{slug(title)}.md').write_text('\n'.join(L), encoding='utf-8', newline='\n')

    groups = defaultdict(list)
    for r in recs:
        for s in r['sources']:
            groups[source_key(s)].append((s['position'], r))
    for key, rows in groups.items():
        rows.sort(key=lambda x: x[0])
        sem, inst = key.split('-', 1)
        L = [f"# {sem} — {inst}", '',
             f"*{len(rows)} problems, in the order they appeared. GENERATED by scripts/compile.py.*", '']
        for _, r in rows:
            L.append(md_problem(r, skills))
        (BY_SOURCE / f'{key}.md').write_text('\n'.join(L), encoding='utf-8', newline='\n')

    unweeked = [r['id'] for r in recs if not r['week']]
    return unweeked


def write_coverage(recs, skills):
    L = ['# Coverage', '',
         '*GENERATED by scripts/compile.py. Problems per week, per skill, and the skills no problem tests.*', '']
    by_week = Counter(r['week'] for r in recs if r['week'])
    L.append('## Problems per week')
    L.append('')
    L.append('| week | title | active | needs-review | retired |')
    L.append('|---|---|---|---|---|')
    for w in range(1, 14):
        rows = [r for r in recs if r['week'] == w]
        st = Counter(r['status'] for r in rows)
        L.append(f"| {w} | {week_title(skills, w)} | {st['active']} | {st['needs-review']} | {st['retired-2e']} |")
    L.append('')

    tagged = sum(1 for r in recs if r['skills'])
    L.append(f'## Skills ({tagged}/{len(recs)} problems tagged)')
    L.append('')
    per_skill = Counter(sid for r in recs if r['status'] != 'retired-2e' for sid in r['skills'])
    untested = []
    for w in range(1, 14):
        wk = skills['weeks'].get(str(w), {})
        L.append(f"### Week {w}: {week_title(skills, w)}")
        L.append('')
        for sid, name in wk.get('skills', {}).items():
            n = per_skill.get(sid, 0)
            mark = '' if n else ' **← untested**'
            L.append(f"- `{sid}` ({n}) {name}{mark}")
            if not n:
                untested.append(sid)
        L.append('')
    L.append(f'**Untested skills: {len(untested)}**' +
             (' — ' + ', '.join(untested) if untested else ''))
    L.append('')
    COVERAGE.write_text('\n'.join(L), encoding='utf-8', newline='\n')
    return untested


# ------------------------------------------------------------------ main

if __name__ == '__main__':
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--check', action='store_true', help='validate only; write nothing')
    a = ap.parse_args()

    errors = V.main()
    if errors:
        sys.exit(f'compile aborted: {errors} validation error(s)')
    if a.check:
        sys.exit(0)

    recs, skills = load()
    write_json(recs, skills)
    unweeked = write_views(recs, skills)
    untested = write_coverage(recs, skills)

    print(f'problems.json   : {len(recs)} records (schema {SCHEMA_VERSION})')
    print(f'by_week/        : 13 files')
    print(f'by_source/      : {len(list(BY_SOURCE.glob("*.md")))} files')
    print(f'COVERAGE.md     : {len(untested)} untested skills')
    if unweeked:
        print(f'no week (not in any by_week view): {", ".join(unweeked)}')
